function [K, M, H, B, Mabc, Kabc] = compute_system(mesh)

% Mass and stiffnes matrices
dof_X = size(mesh.X, 1);
auxones = ones(dof_X, 1);
[K, M] = PGDberkhoffVolumeMatrices(...
    mesh.X,...
    mesh.T,...
    mesh.refelem,...
    auxones,... %for Kint
    auxones,... %for Kxpml
    auxones,... %for Kypml
    auxones,... %for varMint, varMpml
    []);        %No PML elements
K = K{1};
M = M{1};

% Coupled term on exterior boundary for farfield functions
H = coupledMassMatrix_u(...
    mesh.X,...
    mesh.Tb_ext,...
    mesh.T_ext,...
    mesh.refelem);

% Coupled term on exterior boundary for farfield functions
B = mesh.rad_ext * coupledMassMatrix_f(...
    mesh.X_ext,...
    mesh.T_ext,...
    mesh.T,...
    mesh.refelem,...
    mesh.periodic_elem,...
    mesh.elementFaceInfo.ext);

% Mass matrix for farfield functions (1D problem)
Mabc = mesh.rad_ext * massMatrix1D(mesh.X_ext, mesh.T_ext, mesh.refelem, mesh.periodic_elem);

% Stiffness matrix for farfield functions (1D problem)
Kabc = mesh.rad_ext * stiffMatrix1D(mesh.X_ext, mesh.T_ext, mesh.refelem, mesh.periodic_elem);